//WIFI
#define WIFI_SSID "YOUR SSID"
#define WIFI_PW "YOUR PW"

//MQTT
#define MQTT_SERVER "192.168.178.154"
#define MQTT_PORT 1883
#define MQTT_USER "YOUR MQTT USERNAME"
#define MQTT_PW "YOUR MQTT PW"

//OTA
#define OTA_PASSWORD "YOUR OTA PW"
